---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    tag: latest

platform: linux

inputs:
  - name: grootfs-diagnostics-release
  - name: diagnostics

run:
  path: grootfs-diagnostics-release/ci/scripts/print-data.sh
  user: root
