name: ((deployment))

releases:
- name: grootfs-diagnostics
  version: latest

stemcells:
- alias: stemcell
  os: ((stemcell-os))
  version: latest

instance_groups:
- name: grootfs-diagnostics
  instances: 1
  vm_type: ((vm))
  networks:
  - name: ((network))
  azs: [((az))]
  stemcell: stemcell
  jobs:
  - name: dmon
    release: grootfs-diagnostics
    properties:
      dmon:
        dir_to_check: /tmp/

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 1000-240000
  update_watch_time: 1000-240000
