- type: replace
  path: /releases/-
  value:
    name: grootfs-diagnostics
    version: latest

- type: replace
  path: /instance_groups/name=garden/jobs/-
  value:
    name: dmon
    release: grootfs-diagnostics
    properties:
      dmon:
        dir_to_check: /var/vcap/data/grootfs/store/unprivileged
        metron_endpoint: 127.0.0.1
