resources:
  - name: dstate-event
    type: datadog-event
    source:
      api_key: {{datadog-api-key}}
      application_key: {{datadog-application-key}}
      filter: "Dstate detected"
      #filter: "grootfs-diagnostics: d-state"
  - name: grootfs-diagnostics-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/grootfs-diagnostics-release
      branch: concourse-testing
  - name: slack-alert
    type: slack-notification-docker
    source:
      url: {{slack-alert-url}}
  - name: dstate-diagnostics-tarball
    type: s3
    source:
      bucket: grootfs-dstate-reports
      regexp: "(.*).tar.gz"
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}

jobs:
  - name: dstate
    plan:
      - aggregate:
        - get: dstate-event
          tags: [thanos]
          trigger: true
        - get: grootfs-diagnostics-release
          tags: [thanos]
      - do:
        - task: collect-data
          tags: [thanos]
          file: grootfs-diagnostics-release/ci/tasks/collect-data.yml
          privileged: true
          params:
            BOSH_TARGET: {{bosh-target}}
            BOSH_CLIENT: {{bosh-username}}
            BOSH_CLIENT_SECRET: {{bosh-password}}
            BOSH_CERTIFICATES: {{bosh-certificates}}
            BOSH_DEPLOYMENT: cf
        - put: dstate-diagnostics-tarball
          params:
            file: diagnostics/*.tar.gz
        ensure:
          put: slack-alert
          params:
            channel: "cf-grootfs"
            username: "Santa"
            icon_url: "https://media.giphy.com/media/vTn5ap94xD9nO/giphy.gif"
            text: "<!subteam^S5YHYPBV4|grootfsteam>:: D-STATE DETECTED! :red_circle: :red_circle: :red_circle: :red_circle:"

resource_types:
  - name: datadog-event
    type: docker-image
    source:
      repository: cfgarden/datadog-event-resource
  - name: slack-notification-docker
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource


