resources:
  - name: dstate-event
    type: datadog-event
    source:
      api_key: {{datadog-api-key}}
      application_key: {{datadog-application-key}}
      filter: "Dstate detected"
      #filter: "grootfs-diagnostics: d-state"
  - name: grootfs-diagnostics-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/grootfs-diagnostics-release
      branch: concourse-testing
  - name: slack-alert
    type: slack-notification-docker
    source:
      url: {{slack-alert-url}}
  - name: dstate-diagnostics-tarball
    type: s3
    source:
      bucket: grootfs-bosh-releases
      regexp: "(.*).tar.gz"
      region_name: eu-west-1
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}

jobs:
  - name: dstate
    plan:
      - aggregate:
        - get: dstate-event
          tags: [thanos]
          trigger: true
        - get: grootfs-diagnostics-release
          tags: [thanos]
      - task: collect-data
        tags: [thanos]
        file: grootfs-diagnostics-release/ci/tasks/collect-data.yml
        privileged: true
        params:
          BOSH_TARGET: {{thanos-bosh-target}}
          BOSH_CLIENT: {{thanos-bosh-username}}
          BOSH_CLIENT_SECRET: {{thanos-bosh-password}}
          BOSH_CERTIFICATES: {{thanos-bosh-certificates}}
          BOSH_DEPLOYMENT: cf
      - put: dstate-diagnostics-tarball
        params:
          file: diagnostics/*.tgz
      - put: slack-alert
        params:
          channel: "grootfs"
          text: "D-STATE DETECTED!"

resource_types:
  - name: datadog-event
    type: docker-image
    source:
      repository: cfgarden/datadog-event-resource


