resources:
  - name: dstate-event
    type: datadog-event
    check_every: 30s
    source:
      api_key: {{PROD_DATADOG_API_KEY}}
      application_key: {{datadog-application-key}}
      filter: "grootfs-diagnostics: d-state"
  - name: grootfs-diagnostics-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/grootfs-diagnostics-release
      branch: master
  - name: slack-alert
    type: slack-notification-docker
    source:
      url: {{slack-alert-url}}
  - name: dstate-diagnostics-tarball
    type: s3
    source:
      bucket: grootfs-diagnostics-pws
      regexp: "(.*).tar.gz"
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}

jobs:
  - name: dstate
    plan:
      - aggregate:
        - get: dstate-event
          trigger: true
        - get: grootfs-diagnostics-release
      - do:
        - task: collect-data
          tags: [{{dstate-job-worker-tag}}]
          file: grootfs-diagnostics-release/ci/tasks/collect-data.yml
          privileged: true
          params:
            BOSH_TARGET: {{prod_bosh_target}}
            BOSH_CLIENT: {{prod_bosh_client_id}}
            BOSH_CLIENT_SECRET: {{prod_bosh_client_secret}}
            BOSH_CA_CERT: {{prod_bosh_ca_cert}}
            BOSH_DEPLOYMENT: {{bosh-deployment-name}}
        - aggregate:
          - task: print-data
            file: grootfs-diagnostics-release/ci/tasks/print-data.yml
          - put: dstate-diagnostics-tarball
            params:
              file: diagnostics/*.tar.gz
        ensure:
          put: slack-alert
          params:
            channel: {{dstate-slack-alert-channel}}
            username: "Santa"
            icon_url: "https://media.giphy.com/media/vTn5ap94xD9nO/giphy.gif"
            text: {{dstate-slack-alert-text}}

resource_types:
  - name: datadog-event
    type: docker-image
    source:
      repository: cfgarden/datadog-event-resource
  - name: slack-notification-docker
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource


